/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:9f48b623-c42e-4d5b-82c5-133b782bcfd5",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_2EZQWY552",
    "aws_user_pools_web_client_id": "2qn4qjgsp5vs884tdjdjpefh6g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://jcadcpr22vfbbat77moceprt2y.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zsmidgbe7zgitmiok4sdq3caca",
    "aws_user_files_s3_bucket": "jwgamebucketstorageforimages164210-staging",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
